export NVM_DIR="/Users/z001q83/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export SYMMETRY_DIR="/Users/z001q83/tn/symmetry"
[ -s "$SYMMETRY_DIR/.sh" ] && . "$SYMMETRY_DIR/symmetry.sh"  # This loads symmetry

